import type { CrmPageData } from "@/components/crm/CrmPageTemplate";

export const crmPageData: Record<string, CrmPageData> = {
  "configuration/communication-status": {
    breadcrumb: "CRM / Configuration / Communication Status",
    title: "Communication Status",
    description: "Manage the outcome labels used when logging a call or contact attempt.",
    addLabel: "Add Communication Status",
    columns: [
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Interested", type: "Positive", status: "Active" },
      { name: "Not Interested", type: "Negative", status: "Active" },
      { name: "Call Back Later", type: "Neutral", status: "Active" },
      { name: "No Response", type: "Neutral", status: "Active" },
      { name: "Wrong Number", type: "Negative", status: "Inactive" },
    ],
  },
  "configuration/teams": {
    breadcrumb: "CRM / Configuration / Teams",
    title: "Teams",
    description: "Manage sales teams and their leads.",
    addLabel: "Add Team",
    columns: [
      { key: "team", label: "Team Name" },
      { key: "lead", label: "Team Lead" },
      { key: "members", label: "Members" },
      { key: "branch", label: "Branch" },
    ],
    rows: [
      { team: "Sales Team A", lead: "Rafiq Islam", members: 8, branch: "Gulshan" },
      { team: "Sales Team B", lead: "Farhana Rahman", members: 6, branch: "Uttara" },
      { team: "Sales Team C", lead: "Imran Chowdhury", members: 5, branch: "Chattogram" },
    ],
  },
  "configuration/lead-category": {
    breadcrumb: "CRM / Configuration / Lead Category",
    title: "Lead Category",
    description: "Classify leads by the type of property they're interested in.",
    addLabel: "Add Category",
    columns: [
      { key: "name", label: "Category Name" },
      { key: "description", label: "Description" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Residential", description: "Flats, apartments, houses", status: "Active" },
      { name: "Commercial", description: "Office space, shops", status: "Active" },
      { name: "Industrial", description: "Warehouses, factories", status: "Active" },
      { name: "Land", description: "Plots and land shares", status: "Active" },
    ],
  },
  "configuration/campaign": {
    breadcrumb: "CRM / Configuration / Campaign",
    title: "Campaign",
    description: "Track marketing campaigns that generate leads.",
    addLabel: "Add Campaign",
    columns: [
      { key: "name", label: "Campaign Name" },
      { key: "source", label: "Source" },
      { key: "start", label: "Start Date" },
      { key: "end", label: "End Date" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Facebook Winter Promo", source: "Facebook", start: "2026-11-01", end: "2026-12-31", status: "Active" },
      { name: "Google Ads Q1", source: "Google", start: "2026-01-01", end: "2026-03-31", status: "Completed" },
      { name: "Print Media Launch", source: "Newspaper", start: "2026-06-01", end: "2026-06-30", status: "Completed" },
    ],
  },
  "configuration/profession": {
    breadcrumb: "CRM / Configuration / Profession",
    title: "Profession",
    description: "Manage the profession list used to profile leads.",
    addLabel: "Add Profession",
    columns: [
      { key: "name", label: "Profession Name" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Business Owner", status: "Active" },
      { name: "Service Holder", status: "Active" },
      { name: "Doctor", status: "Active" },
      { name: "Engineer", status: "Active" },
      { name: "Government Employee", status: "Active" },
    ],
  },
  "configuration/lead-source": {
    breadcrumb: "CRM / Configuration / Lead Source",
    title: "Lead Source",
    description: "Manage the channels a lead can originate from.",
    addLabel: "Add Source",
    columns: [
      { key: "name", label: "Source Name" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Facebook", type: "Online", status: "Active" },
      { name: "Website", type: "Online", status: "Active" },
      { name: "Referral", type: "Offline", status: "Active" },
      { name: "Walk-in", type: "Offline", status: "Active" },
      { name: "Cold Call", type: "Offline", status: "Active" },
    ],
  },
  "configuration/offers": {
    breadcrumb: "CRM / Configuration / Offers",
    title: "Offers",
    description: "Manage promotional offers shown to leads.",
    addLabel: "Add Offer",
    columns: [
      { key: "name", label: "Offer Name" },
      { key: "discount", label: "Discount" },
      { key: "validTill", label: "Valid Till" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Eid Offer", discount: "5% off", validTill: "2026-04-15", status: "Active" },
      { name: "New Year Discount", discount: "3% off", validTill: "2027-01-15", status: "Upcoming" },
      { name: "Early Booking", discount: "Free parking", validTill: "2026-12-31", status: "Active" },
    ],
  },
  "configuration/area": {
    breadcrumb: "CRM / Configuration / Area",
    title: "Area",
    description: "Manage the location/area list used to tag leads and properties.",
    addLabel: "Add Area",
    columns: [
      { key: "name", label: "Area Name" },
      { key: "city", label: "City" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Gulshan", city: "Dhaka", status: "Active" },
      { name: "Banani", city: "Dhaka", status: "Active" },
      { name: "Uttara", city: "Dhaka", status: "Active" },
      { name: "Bashundhara", city: "Dhaka", status: "Active" },
      { name: "Agrabad", city: "Chattogram", status: "Active" },
    ],
  },
  "configuration/lead-stage": {
    breadcrumb: "CRM / Configuration / Lead Stage",
    title: "Lead Stage",
    description: "Manage the pipeline stages a lead moves through.",
    addLabel: "Add Stage",
    columns: [
      { key: "name", label: "Stage Name" },
      { key: "order", label: "Order" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "New", order: 1, status: "Active" },
      { name: "Contacted", order: 2, status: "Active" },
      { name: "Qualified", order: 3, status: "Active" },
      { name: "Negotiation", order: 4, status: "Active" },
      { name: "Won", order: 5, status: "Active" },
      { name: "Lost", order: 6, status: "Active" },
    ],
  },
  "configuration/project": {
    breadcrumb: "CRM / Configuration / Project",
    title: "Project",
    description: "Manage the list of projects leads can be linked to.",
    addLabel: "Add Project",
    columns: [
      { key: "name", label: "Project Name" },
      { key: "location", label: "Location" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { name: "Skyline Residency", location: "Gulshan, Dhaka", type: "Residential", status: "Under Construction" },
      { name: "Green Valley Tower", location: "Bashundhara, Dhaka", type: "Residential", status: "Under Construction" },
      { name: "Riverside Heights", location: "Chattogram", type: "Residential", status: "Ready" },
    ],
  },
  "configuration/price-range": {
    breadcrumb: "CRM / Configuration / Price Range",
    title: "Price Range",
    description: "Manage the budget brackets used to filter leads and properties.",
    addLabel: "Add Range",
    columns: [
      { key: "name", label: "Range Name" },
      { key: "min", label: "Min Price" },
      { key: "max", label: "Max Price" },
    ],
    rows: [
      { name: "Under 50L", min: "\u09F30", max: "\u09F350,00,000" },
      { name: "50L - 1Cr", min: "\u09F350,00,000", max: "\u09F31,00,00,000" },
      { name: "1Cr - 2Cr", min: "\u09F31,00,00,000", max: "\u09F32,00,00,000" },
      { name: "Above 2Cr", min: "\u09F32,00,00,000", max: "\u2014" },
    ],
  },

  "lead/lead-list": {
    breadcrumb: "CRM / Lead / Lead List",
    title: "Lead List",
    description: "All leads currently in the system.",
    addLabel: "Add Lead",
    columns: [
      { key: "id", label: "Lead ID" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "source", label: "Source" },
      { key: "stage", label: "Stage" },
      { key: "agent", label: "Assigned Agent" },
    ],
    rows: [
      { id: "L260907-0022", name: "Serena Ahmed", phone: "01711-000001", source: "Facebook", stage: "Contacted", agent: "Admin" },
      { id: "L260906-0020", name: "Sharmin Akter", phone: "01711-000002", source: "Website", stage: "New", agent: "Sabbir" },
      { id: "L260906-0018", name: "Rafiq Islam", phone: "01711-000003", source: "Referral", stage: "Qualified", agent: "Admin" },
      { id: "L260904-0015", name: "Nusrat Jahan", phone: "01711-000004", source: "Walk-in", stage: "Negotiation", agent: "Sabbir" },
    ],
  },
  "lead/junk-lead": {
    breadcrumb: "CRM / Lead / Junk Lead",
    title: "Junk Lead",
    description: "Leads marked as junk (invalid, duplicate, or spam).",
    columns: [
      { key: "id", label: "Lead ID" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "reason", label: "Reason" },
      { key: "markedBy", label: "Marked By" },
      { key: "date", label: "Date" },
    ],
    rows: [
      { id: "L260820-0004", name: "Test User", phone: "01700-000000", reason: "Invalid number", markedBy: "Admin", date: "2026-08-20" },
      { id: "L260818-0002", name: "ggg", phone: "0000000000", reason: "Duplicate", markedBy: "Sabbir", date: "2026-08-18" },
    ],
  },
  "lead/transfer-history": {
    breadcrumb: "CRM / Lead / Transfer History",
    title: "Transfer History",
    description: "History of leads reassigned between agents.",
    columns: [
      { key: "id", label: "Lead ID" },
      { key: "name", label: "Name" },
      { key: "from", label: "From Agent" },
      { key: "to", label: "To Agent" },
      { key: "by", label: "Transferred By" },
      { key: "date", label: "Date" },
    ],
    rows: [
      { id: "L260906-0018", name: "Rafiq Islam", from: "Sabbir", to: "Admin", by: "Admin", date: "2026-09-06" },
      { id: "L260827-0012", name: "Golam Gaus", from: "Admin", to: "Sabbir", by: "Admin", date: "2026-08-27" },
    ],
  },

  "call-center/follow-up": {
    breadcrumb: "CRM / Call Center / Follow Up",
    title: "Follow Up",
    description: "Scheduled and completed follow-up calls.",
    addLabel: "Add Follow-up",
    columns: [
      { key: "id", label: "Lead ID" },
      { key: "name", label: "Name" },
      { key: "date", label: "Follow-up Date" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status" },
      { key: "agent", label: "Agent" },
    ],
    rows: [
      { id: "L260827-0012", name: "Golam Gaus", date: "2026-09-10", type: "Call", status: "Due", agent: "Admin" },
      { id: "L260825-0009", name: "Nusrat Jahan", date: "2026-09-09", type: "Visit", status: "Completed", agent: "Sabbir" },
    ],
  },
  "call-center/call-report": {
    breadcrumb: "CRM / Call Center / Call Report",
    title: "Call Report",
    description: "Daily call volume summary by agent.",
    columns: [
      { key: "date", label: "Date" },
      { key: "agent", label: "Agent" },
      { key: "total", label: "Total Calls" },
      { key: "connected", label: "Connected" },
      { key: "notConnected", label: "Not Connected" },
    ],
    rows: [
      { date: "2026-09-10", agent: "Admin", total: 24, connected: 18, notConnected: 6 },
      { date: "2026-09-10", agent: "Sabbir", total: 19, connected: 14, notConnected: 5 },
    ],
  },
  "call-center/call-report-details": {
    breadcrumb: "CRM / Call Center / Call Report Details",
    title: "Call Report Details",
    description: "Individual call log entries.",
    columns: [
      { key: "id", label: "Lead ID" },
      { key: "name", label: "Name" },
      { key: "agent", label: "Agent" },
      { key: "time", label: "Call Time" },
      { key: "duration", label: "Duration" },
      { key: "outcome", label: "Outcome" },
    ],
    rows: [
      { id: "L260907-0022", name: "Serena Ahmed", agent: "Admin", time: "10:14 AM", duration: "3m 12s", outcome: "Interested" },
      { id: "L260906-0020", name: "Sharmin Akter", agent: "Sabbir", time: "9:58 AM", duration: "1m 40s", outcome: "Call Back Later" },
    ],
  },
  "call-center/call-assign-history": {
    breadcrumb: "CRM / Call Center / Call Assign History",
    title: "Call Assign History",
    description: "History of call task assignments to agents.",
    columns: [
      { key: "id", label: "Lead ID" },
      { key: "assignedTo", label: "Assigned To" },
      { key: "assignedBy", label: "Assigned By" },
      { key: "date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { id: "L260906-0018", assignedTo: "Admin", assignedBy: "System", date: "2026-09-06", status: "Completed" },
      { id: "L260904-0015", assignedTo: "Sabbir", assignedBy: "Admin", date: "2026-09-04", status: "Pending" },
    ],
  },

  "task-visit/task-visit-list": {
    breadcrumb: "CRM / Task/Visit / Task/Visit List",
    title: "Task/Visit List",
    description: "All scheduled tasks and site visits.",
    addLabel: "Add Task/Visit",
    columns: [
      { key: "id", label: "Task/Visit ID" },
      { key: "lead", label: "Lead Name" },
      { key: "type", label: "Type" },
      { key: "date", label: "Scheduled Date" },
      { key: "agent", label: "Assigned Agent" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { id: "TV-1042", lead: "Serena Ahmed", type: "Site Visit", date: "2026-09-12", agent: "Admin", status: "Scheduled" },
      { id: "TV-1039", lead: "Rafiq Islam", type: "Meeting", date: "2026-09-08", agent: "Sabbir", status: "Completed" },
    ],
  },
  "task-visit/deal-negotiation-activity": {
    breadcrumb: "CRM / Task/Visit / Deal Negotiation Activity",
    title: "Deal Negotiation Activity",
    description: "Ongoing negotiation activity per lead.",
    columns: [
      { key: "lead", label: "Lead Name" },
      { key: "property", label: "Property" },
      { key: "stage", label: "Negotiation Stage" },
      { key: "lastUpdate", label: "Last Update" },
      { key: "agent", label: "Agent" },
    ],
    rows: [
      { lead: "Nusrat Jahan", property: "Unit 4B, Skyline Residency", stage: "Price Discussion", lastUpdate: "2026-09-09", agent: "Sabbir" },
      { lead: "Golam Gaus", property: "Unit 2A, Palm Court", stage: "Final Offer", lastUpdate: "2026-09-08", agent: "Admin" },
    ],
  },
  "task-visit/task-visit-summary-report": {
    breadcrumb: "CRM / Task/Visit / Task/Visit Summary Report",
    title: "Task/Visit Summary Report",
    description: "Aggregated task/visit completion by agent.",
    columns: [
      { key: "agent", label: "Agent" },
      { key: "total", label: "Total Tasks" },
      { key: "completed", label: "Completed" },
      { key: "pending", label: "Pending" },
      { key: "missed", label: "Missed" },
    ],
    rows: [
      { agent: "Admin", total: 32, completed: 27, pending: 4, missed: 1 },
      { agent: "Sabbir", total: 28, completed: 21, pending: 5, missed: 2 },
    ],
  },
  "task-visit/task-visit-details-report": {
    breadcrumb: "CRM / Task/Visit / Task/Visit Details Report",
    title: "Task/Visit Details Report",
    description: "Detailed log of individual tasks and visits.",
    columns: [
      { key: "date", label: "Date" },
      { key: "lead", label: "Lead Name" },
      { key: "type", label: "Type" },
      { key: "agent", label: "Agent" },
      { key: "outcome", label: "Outcome" },
    ],
    rows: [
      { date: "2026-09-08", lead: "Rafiq Islam", type: "Meeting", agent: "Sabbir", outcome: "Positive" },
      { date: "2026-09-06", lead: "Sharmin Akter", type: "Call", agent: "Admin", outcome: "Rescheduled" },
    ],
  },

  "property/flat": {
    breadcrumb: "CRM / Property / Flat",
    title: "Flat",
    description: "Manage flat inventory across all projects.",
    addLabel: "Add Flat",
    columns: [
      { key: "flatNo", label: "Flat No" },
      { key: "project", label: "Project" },
      { key: "floor", label: "Floor" },
      { key: "size", label: "Size (sqft)" },
      { key: "status", label: "Status" },
      { key: "price", label: "Price" },
    ],
    rows: [
      { flatNo: "4B", project: "Skyline Residency", floor: 4, size: 1450, status: "Ready", price: "\u09F31,45,00,000" },
      { flatNo: "2A", project: "Palm Court", floor: 2, size: 1100, status: "Booked", price: "\u09F398,00,000" },
      { flatNo: "7C", project: "Aurora Heights", floor: 7, size: 1850, status: "Available", price: "\u09F31,85,00,000" },
    ],
  },
  "property/land": {
    breadcrumb: "CRM / Property / Land",
    title: "Land",
    description: "Manage land plot inventory.",
    addLabel: "Add Land",
    columns: [
      { key: "plotNo", label: "Plot No" },
      { key: "location", label: "Location" },
      { key: "size", label: "Size (Katha)" },
      { key: "status", label: "Status" },
      { key: "price", label: "Price" },
    ],
    rows: [
      { plotNo: "14B", location: "Purbachal, Dhaka", size: 5, status: "Available", price: "\u09F32,50,00,000" },
      { plotNo: "R-09", location: "Savar, Dhaka", size: 10, status: "Sold", price: "\u09F34,00,00,000" },
    ],
  },
  "property/booking": {
    breadcrumb: "CRM / Property / Booking",
    title: "Booking",
    description: "Manage property bookings and reservation status.",
    addLabel: "Add Booking",
    columns: [
      { key: "id", label: "Booking ID" },
      { key: "client", label: "Client Name" },
      { key: "unit", label: "Unit" },
      { key: "date", label: "Booking Date" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { id: "BK-2201", client: "Nusrat Jahan", unit: "Unit 4B, Skyline Residency", date: "2026-08-15", status: "Confirmed" },
      { id: "BK-2198", client: "Golam Gaus", unit: "Unit 2A, Palm Court", date: "2026-08-10", status: "Pending" },
    ],
  },
  "property/sale-offer": {
    breadcrumb: "CRM / Property / Sale Offer",
    title: "Sale Offer",
    description: "Manage active sale offers on units.",
    addLabel: "Add Sale Offer",
    columns: [
      { key: "id", label: "Offer ID" },
      { key: "client", label: "Client Name" },
      { key: "unit", label: "Unit" },
      { key: "price", label: "Offer Price" },
      { key: "status", label: "Status" },
      { key: "date", label: "Date" },
    ],
    rows: [
      { id: "SO-3301", client: "Rafiq Islam", unit: "Unit 7C, Aurora Heights", price: "\u09F31,80,00,000", status: "Sent", date: "2026-09-05" },
      { id: "SO-3298", client: "Sharmin Akter", unit: "Plot 14B, Purbachal", price: "\u09F32,40,00,000", status: "Accepted", date: "2026-09-01" },
    ],
  },

  "reports/user-wise-report": {
    breadcrumb: "CRM / Reports / User Wise Report",
    title: "User Wise Report",
    description: "Lead and conversion performance broken down by agent.",
    columns: [
      { key: "agent", label: "Agent" },
      { key: "total", label: "Total Leads" },
      { key: "converted", label: "Converted" },
      { key: "rate", label: "Conversion Rate" },
    ],
    rows: [
      { agent: "Admin", total: 84, converted: 22, rate: "26.2%" },
      { agent: "Sabbir", total: 61, converted: 14, rate: "23.0%" },
    ],
  },
  "reports/user-active-report": {
    breadcrumb: "CRM / Reports / User Activity Report",
    title: "User Activity Report",
    description: "Login and activity summary per user.",
    columns: [
      { key: "agent", label: "Agent" },
      { key: "logins", label: "Logins" },
      { key: "calls", label: "Calls Made" },
      { key: "lastActive", label: "Last Active" },
    ],
    rows: [
      { agent: "Admin", logins: 42, calls: 210, lastActive: "2026-09-11 10:20 AM" },
      { agent: "Sabbir", logins: 35, calls: 178, lastActive: "2026-09-11 9:45 AM" },
    ],
  },
  "reports/sales-pipeline-funnel-report": {
    breadcrumb: "CRM / Reports / Sales Pipeline Funnel Report",
    title: "Sales Pipeline Funnel Report",
    description: "Lead count and conversion percentage by pipeline stage.",
    columns: [
      { key: "stage", label: "Stage" },
      { key: "count", label: "Lead Count" },
      { key: "conversion", label: "Conversion %" },
    ],
    rows: [
      { stage: "New", count: 145, conversion: "100%" },
      { stage: "Contacted", count: 98, conversion: "67.6%" },
      { stage: "Qualified", count: 54, conversion: "37.2%" },
      { stage: "Negotiation", count: 28, conversion: "19.3%" },
      { stage: "Won", count: 16, conversion: "11.0%" },
    ],
  },
  "reports/team-reports": {
    breadcrumb: "CRM / Reports / Team Reports",
    title: "Team Reports",
    description: "Performance summary broken down by team.",
    columns: [
      { key: "team", label: "Team" },
      { key: "leads", label: "Total Leads" },
      { key: "closed", label: "Deals Closed" },
      { key: "revenue", label: "Revenue" },
    ],
    rows: [
      { team: "Sales Team A", leads: 112, closed: 18, revenue: "\u09F32.4Cr" },
      { team: "Sales Team B", leads: 87, closed: 12, revenue: "\u09F31.6Cr" },
    ],
  },
  "reports/interested-flat-land-requirements": {
    breadcrumb: "CRM / Reports / Interested Flat/Land Requirements",
    title: "Interested Flat/Land Requirements",
    description: "Client requirement profiles for property matching.",
    columns: [
      { key: "lead", label: "Lead Name" },
      { key: "type", label: "Requirement Type" },
      { key: "budget", label: "Budget" },
      { key: "area", label: "Preferred Area" },
    ],
    rows: [
      { lead: "Serena Ahmed", type: "Flat", budget: "\u09F31.2Cr - \u09F31.5Cr", area: "Gulshan" },
      { lead: "Rafiq Islam", type: "Land", budget: "\u09F32Cr - \u09F32.5Cr", area: "Purbachal" },
    ],
  },
  "reports/sales-probability": {
    breadcrumb: "CRM / Reports / Sales Probability",
    title: "Sales Probability",
    description: "Estimated close probability per active deal.",
    columns: [
      { key: "lead", label: "Lead Name" },
      { key: "stage", label: "Stage" },
      { key: "probability", label: "Probability %" },
      { key: "expectedClose", label: "Expected Close Date" },
    ],
    rows: [
      { lead: "Nusrat Jahan", stage: "Negotiation", probability: "70%", expectedClose: "2026-09-20" },
      { lead: "Golam Gaus", stage: "Final Offer", probability: "85%", expectedClose: "2026-09-15" },
    ],
  },
  "reports/flat-land-sale-report": {
    breadcrumb: "CRM / Reports / Flat/Land Sale Report",
    title: "Flat/Land Sale Report",
    description: "Completed sales across flats and land.",
    columns: [
      { key: "unit", label: "Unit" },
      { key: "type", label: "Type" },
      { key: "buyer", label: "Buyer" },
      { key: "price", label: "Sale Price" },
      { key: "date", label: "Sale Date" },
    ],
    rows: [
      { unit: "Unit 2A, Palm Court", type: "Flat", buyer: "Golam Gaus", price: "\u09F398,00,000", date: "2026-08-30" },
      { unit: "Plot R-09, Savar", type: "Land", buyer: "Farhana Rahman", price: "\u09F34,00,00,000", date: "2026-08-22" },
    ],
  },
  "reports/missed-followup-visit-summary": {
    breadcrumb: "CRM / Reports / Missed Followup/Visit Summary",
    title: "Missed Followup/Visit Summary",
    description: "Agents with missed follow-ups or visits in the selected range.",
    columns: [
      { key: "agent", label: "Agent" },
      { key: "missedFollowups", label: "Missed Follow-ups" },
      { key: "missedVisits", label: "Missed Visits" },
      { key: "range", label: "Date Range" },
    ],
    rows: [
      { agent: "Admin", missedFollowups: 3, missedVisits: 0, range: "Sep 1 - Sep 11" },
      { agent: "Sabbir", missedFollowups: 1, missedVisits: 1, range: "Sep 1 - Sep 11" },
    ],
  },
  "reports/deal-negotiation-reports": {
    breadcrumb: "CRM / Reports / Deal Negotiation Report",
    title: "Deal Negotiation Report",
    description: "Status of all deals currently in negotiation.",
    columns: [
      { key: "lead", label: "Lead Name" },
      { key: "property", label: "Property" },
      { key: "stage", label: "Stage" },
      { key: "lastPrice", label: "Last Negotiated Price" },
      { key: "status", label: "Status" },
    ],
    rows: [
      { lead: "Nusrat Jahan", property: "Unit 4B, Skyline Residency", stage: "Price Discussion", lastPrice: "\u09F31,40,00,000", status: "Ongoing" },
      { lead: "Golam Gaus", property: "Unit 2A, Palm Court", stage: "Final Offer", lastPrice: "\u09F396,00,000", status: "Ongoing" },
    ],
  },

  "kpi/employee-kpi-setting": {
    breadcrumb: "CRM / KPI / Employee KPI Setting",
    title: "Employee KPI Setting",
    description: "Configure KPI targets and weighting per employee.",
    addLabel: "Add KPI",
    columns: [
      { key: "employee", label: "Employee" },
      { key: "metric", label: "KPI Metric" },
      { key: "target", label: "Target" },
      { key: "weight", label: "Weight %" },
    ],
    rows: [
      { employee: "Admin", metric: "Calls per day", target: 25, weight: "30%" },
      { employee: "Sabbir", metric: "Site visits per week", target: 5, weight: "25%" },
    ],
  },
  "kpi/reports": {
    breadcrumb: "CRM / KPI / Reports",
    title: "Employee & Team Call Reports",
    description: "KPI achievement summary by employee.",
    columns: [
      { key: "employee", label: "Employee" },
      { key: "callsTarget", label: "Calls Target" },
      { key: "callsAchieved", label: "Calls Achieved" },
      { key: "visitsTarget", label: "Visits Target" },
      { key: "visitsAchieved", label: "Visits Achieved" },
      { key: "score", label: "Score" },
    ],
    rows: [
      { employee: "Admin", callsTarget: 500, callsAchieved: 468, visitsTarget: 20, visitsAchieved: 18, score: "92%" },
      { employee: "Sabbir", callsTarget: 450, callsAchieved: 401, visitsTarget: 20, visitsAchieved: 15, score: "84%" },
    ],
  },
};
