import React from "react";
import {
  AppstoreOutlined,
  FileOutlined,
  EditOutlined,
  EyeOutlined,
  DollarOutlined,
  CalculatorOutlined,
  FileTextOutlined,
  QuestionCircleOutlined,
  ShoppingCartOutlined,
  SearchOutlined,
  UserAddOutlined,
  CalendarOutlined,
  PlusOutlined,
  DownloadOutlined,
  ExportOutlined,
  GiftOutlined,
  SendOutlined,
  BarChartOutlined,
  InfoCircleOutlined,
  SettingOutlined,
  LogoutOutlined,
  ProfileOutlined,
  ShopOutlined,
  GlobalOutlined,
  ClockCircleOutlined,
  RollbackOutlined,
  TagOutlined,
  BuildOutlined,
  BookOutlined,
  BankOutlined,
  UserOutlined,
  UserDeleteOutlined,
  BarcodeOutlined,
  MessageOutlined,
  ScanOutlined,
  PrinterOutlined,
  ToolOutlined,
  InboxOutlined,
  PictureOutlined,
  RiseOutlined,
  ExclamationCircleOutlined,
  TeamOutlined,
  CrownOutlined,
  ShoppingOutlined,
  UserSwitchOutlined,
  FileTextOutlined as FileTextIcon,
} from "@ant-design/icons";

export function getAntIcon(iconName: string | undefined): React.ReactNode {
  if (!iconName) return null;
  const iconMap: Record<string, React.ReactNode> = {
    dashboard: <AppstoreOutlined />,
    file: <FileOutlined />,
    edit: <EditOutlined />,
    eye: <EyeOutlined />,
    "dollar-sign": <DollarOutlined />,
    calculator: <CalculatorOutlined />,
    "file-text": <FileTextOutlined />,
    "help-circle": <QuestionCircleOutlined />,
    "shopping-cart": <ShoppingCartOutlined />,
    search: <SearchOutlined />,
    "user-plus": <UserAddOutlined />,
    calendar: <CalendarOutlined />,
    add: <PlusOutlined />,
    purchase: <ShoppingCartOutlined />,
    import: <DownloadOutlined />,
    distribute: <ExportOutlined />,
    goods: <GiftOutlined />,
    send: <SendOutlined />,
    receive: <DownloadOutlined />,
    salary: <DollarOutlined />,
    report: <BarChartOutlined />,
    status: <InfoCircleOutlined />,
    accounts: <CalculatorOutlined />,
    payroll: <DollarOutlined />,
    reports: <BarChartOutlined />,
    help: <QuestionCircleOutlined />,
    settings: <SettingOutlined />,
    profile: <ProfileOutlined />,
    logout: <LogoutOutlined />,
    shop: <ShopOutlined />,
    brand: <GiftOutlined />,
    supplier: <ExportOutlined />,
    bankAccount: <DollarOutlined />,
    employeeInfo: <UserOutlined />,
    resignation: <UserOutlined />,
    designation: <UserOutlined />,
    // New icons for submenus
    "folder-open": <FileOutlined />,
    setting: <SettingOutlined />,
    download: <DownloadOutlined />,
    global: <GlobalOutlined />,
    export: <ExportOutlined />,
    "info-circle": <InfoCircleOutlined />,
    "clock-circle": <ClockCircleOutlined />,
    rollback: <RollbackOutlined />,
    plus: <PlusOutlined />,
    tag: <TagOutlined />,
    build: <BuildOutlined />,
    book: <BookOutlined />,
    bank: <BankOutlined />,
    user: <UserOutlined />,
    "user-delete": <UserDeleteOutlined />,
    barcode: <BarcodeOutlined />,
    message: <MessageOutlined />,
    scan: <ScanOutlined />,
    printer: <PrinterOutlined />,
    tool: <ToolOutlined />,
    box: <InboxOutlined />,
    picture: <PictureOutlined />,
    dollar: <DollarOutlined />,
    rise: <RiseOutlined />,
    "exclamation-circle": <ExclamationCircleOutlined />,
    team: <TeamOutlined />,
    crown: <CrownOutlined />,
    "bar-chart": <BarChartOutlined />,
    "question-circle": <QuestionCircleOutlined />,
    // Additional icons for specific menu items
    shopping: <ShoppingOutlined />,
    "user-switch": <UserSwitchOutlined />,
    // Placeholder icons for navbar items
    attendance: <ClockCircleOutlined />,
    change: <SettingOutlined />,
    "add-new": <PlusOutlined />,
  };
  return iconMap[iconName] || <UserOutlined />;
}
